#!/bin/bash

ES_URL="http://localhost:9200"
ES_USERNAME="elastic"
ES_PASSWORD="camunda"
S3_BUCKET_NAME="dave-c8"
TASKLIST_BACKUP_SNAPSHOT_REPO_NAME="tasklist_repo"
OPERATE_BACKUP_SNAPSHOT_REPO_NAME="operate_repo"
OPTIMIZE_BACKUP_SNAPSHOT_REPO_NAME="optimize_repo"
ZEEBE_BACKUP_SNAPSHOT_REPO_NAME="zeebe_repo"

ZEEBE_MANAGEMENT_URL="http://localhost:9600"

CURL_SECURITY_OPTIONS="--user ${ES_USERNAME}:${ES_PASSWORD}"
CURL_EXTRA_OPTIONS=""

VERSION=0.0.1
LOG_VERBOSITY='INFO'

BACKUP_ID=$(date +"%Y%m%d%H%M%S")
BACKUP_COUNTER=0
TIMESTAMP=$(date +"%Y%m%d%H%M%S")

TASKLIST_BACKUP_ES_URL="${ES_URL}"
TASKLIST_BACKUP_ES_USER="${ES_USER}"
TASKLIST_BACKUP_ES_PASSWORD="${ES_PASSWORD}"
TASKLIST_BACKUP_SNAPSHOT_REPO_ENDPOINT="${TASKLIST_BACKUP_ES_URL}/_snapshot/${TASKLIST_BACKUP_SNAPSHOT_REPO_NAME}"

OPERATE_BACKUP_ES_URL="${ES_URL}"
OPERATE_BACKUP_ES_USER="${ES_USER}"
OPERATE_BACKUP_ES_PASSWORD="${ES_PASSWORD}"
OPERATE_BACKUP_SNAPSHOT_REPO_ENDPOINT="${OPERATE_BACKUP_ES_URL}/_snapshot/${OPERATE_BACKUP_SNAPSHOT_REPO_NAME}"

OPTIMIZE_BACKUP_ES_URL="${ES_URL}"
OPTIMIZE_BACKUP_ES_USER="${ES_USER}"
OPTIMIZE_BACKUP_ES_PASSWORD="${ES_PASSWORD}"
OPTIMIZE_BACKUP_SNAPSHOT_REPO_ENDPOINT="${OPTIMIZE_BACKUP_ES_URL}/_snapshot/${OPTIMIZE_BACKUP_SNAPSHOT_REPO_NAME}"

ZEEBE_BACKUP_ES_URL="${ES_URL}"
ZEEBE_BACKUP_ES_USER="${ES_USER}"
ZEEBE_BACKUP_ES_PASSWORD="${ES_PASSWORD}"
ZEEBE_BACKUP_SNAPSHOT_REPO_ENDPOINT="${ZEEBE_BACKUP_ES_URL}/_snapshot/${ZEEBE_BACKUP_SNAPSHOT_REPO_NAME}"
ZEEBE_PAUSE_EXPORT_ENDPOINT="${ZEEBE_MANAGEMENT_URL}/actuator/exporting/pause"
ZEEBE_RESUME_EXPORT_ENDPOINT="${ZEEBE_MANAGEMENT_URL}/actuator/exporting/resume"
ZEEBE_BACKUP_ENDPOINT="${ZEEBE_MANAGEMENT_URL}/actuator/backup"