# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  ingress:
    enabled: true
    className: nginx
    host: "YOUR_HOSTNAME"
    tls:
      enabled: true
      secretName: "tls-secret"
  identity:
    auth:
      publicIssuerUrl: "https://YOUR_HOSTNAME/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://YOUR_HOSTNAME/operate"
      tasklist:
        redirectUrl: "https://YOUR_HOSTNAME/tasklist"
      optimize:
        redirectUrl: "https://YOUR_HOSTNAME/optimize"
      connectors:
        redirectUrl: "https://YOUR_HOSTNAME/connectors"
      webModeler:
        redirectUrl: "https://YOUR_HOSTNAME/modeler"

identity:
  contextPath: "/identity"
  fullURL: "https://YOUR_HOSTNAME/identity"
  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://YOUR_HOSTNAME/auth"

operate:
  enabled: true
  contextPath: "/operate"
  migration:
    enabled: false
  env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME
      value: "ES_USERNAME"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD
      value: "ES_PASSWORD"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_HEALTHCHECKENABLED
      value: "false"
    - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_USERNAME
      value: "operate"
    - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PASSWORD
      value: "camunda"
    - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_HEALTHCHECKENABLED
      value: "false"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_CREATESCHEMA
      value: "false"


tasklist:
  enabled: true
  contextPath: "/tasklist"
  env:
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_USERNAME
      value: "ES_USERNAME"
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_PASSWORD
      value: "ES_PASSWORD"
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_HEALTHCHECKENABLED
      value: "false"
    - name: CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_USERNAME
      value: "tasklist"
    - name: CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_PASSWORD
      value: "camunda"
    - name: CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_HEALTHCHECKENABLED
      value: "false"
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_CREATESCHEMA
      value: "false"

optimize:
  enabled: false

connectors:
  enabled: false
  inbound:
    mode: oauth
  contextPath: "/connectors"

webModeler:
  enabled: true
  contextPath: "/modeler"
  image:
    pullSecrets:
      - name: camunda-docker-registry
  restapi:
    mail:
      fromAddress: YOUR_EMAIL
  env:
    - name: PLAY_ENABLED
      value: true

postgresql:
  enabled: true

prometheusServiceMonitor:
  enabled: true

zeebeGateway:
  enabled: false
  contextPath: "/rest"
  ingress:
    grpc:
      enabled: true
      host: "YOUR_HOSTNAME"
      tls:
        enabled: true
        secretName: "tls-secret"
    rest:
      enabled: true
      host: "YOUR_HOSTNAME"
      path: "/rest"
      tls:
        enabled: true
        secretName: "tls-secret"
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_PROBETIMEOUT
      value: "500ms"

zeebe:
  enabled: false
  clusterSize: 1
  partitionCount: 3
  replicationFactor: 1
  pvcSize: 10Gi
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBETIMEOUT
      value: "500ms"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_USERNAME
      value: ES_USERNAME
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_PASSWORD
      value: ES_PASSWORD
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_CREATETEMPLATE
      value: "false"

elasticsearch:
  security:
    enabled: true
    elasticPassword: "ES_ADMIN_PASSWORD"
    tls:
      autoGenerated: true
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  global:
    kibanaEnabled: true
  kibana:
    image:
      tag: 8.15.4
    elasticsearch:
      security:
        auth:
          enabled: true
          createSystemUser: true
          # default in the elasticsearch chart is elastic
          kibanaUsername: "elastic"
          kibanaPassword: "camunda"
          elasticsearchPasswordSecret: camunda-elasticsearch
        tls:
          enabled: false
    configuration:
      server:
        basePath: "/kibana"
        rewriteBasePath: true
    readinessProbe:
      enabled: false

